# Generated by Django 4.1.5 on 2023-02-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
